// <auto-generated />
using System;
using GRP.Services.WaterTankCalculator.DAL.Concrete.EntityFrameworkCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GRP.Services.WaterTankCalculator.Migrations
{
    [DbContext(typeof(WaterTankCalculatorDbContext))]
    partial class WaterTankCalculatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.Constants", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("GRPKgPrice")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<float>("Transportation")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Constants");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.Defaults.ModuleDefault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ModuleDefaults");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.Defaults.ProductDefault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ProductDefaults");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.Defaults.RATDefault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("DIP")
                        .HasColumnType("real");

                    b.Property<float>("DKPS")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("LC")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<float>("RUB")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("RATDefaults");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.History.CalculateModelHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<Guid?>("CalculationHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EdgeModelHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<float>("Length")
                        .HasColumnType("real");

                    b.Property<int>("PlinthType")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("TotalCostHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CalculationHistoryId");

                    b.ToTable("CalculateModelHistories");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.History.CalculationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<Guid?>("CompnyId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConstantsHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("FullTotal")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<float>("KDV")
                        .HasColumnType("real");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConstantsHistoryId")
                        .IsUnique()
                        .HasFilter("[ConstantsHistoryId] IS NOT NULL");

                    b.ToTable("CalculationHistories");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.History.ConstantsHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<Guid?>("CalculationHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Dollar")
                        .HasColumnType("real");

                    b.Property<float>("GRPKgPrice")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<float>("Transportation")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ConstantsHistories");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.History.EdgeModelHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<Guid?>("CalculateModelHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Capacity")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Edge_Bottom")
                        .HasColumnType("real");

                    b.Property<float>("Edge_Side")
                        .HasColumnType("real");

                    b.Property<float>("Edge_Top")
                        .HasColumnType("real");

                    b.Property<float>("Interior_Bottom")
                        .HasColumnType("real");

                    b.Property<float>("Interior_Side")
                        .HasColumnType("real");

                    b.Property<float>("Interior_Top")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<float>("Outside_Bottom")
                        .HasColumnType("real");

                    b.Property<float>("Outside_Side")
                        .HasColumnType("real");

                    b.Property<float>("Outside_Top")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CalculateModelHistoryId")
                        .IsUnique()
                        .HasFilter("[CalculateModelHistoryId] IS NOT NULL");

                    b.ToTable("EdgeModelHistories");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.History.ModuleHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<Guid?>("CalculateModelHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModuleDefaultKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("int");

                    b.Property<float>("TotalWeight")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CalculateModelHistoryId");

                    b.HasIndex("ModuleDefaultKey");

                    b.ToTable("ModuleHistories");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.History.ProductHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<Guid?>("CalculateModelHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ProductDefaultKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CalculateModelHistoryId");

                    b.HasIndex("ProductDefaultKey");

                    b.ToTable("ProductHistories");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.History.RATHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<Guid?>("CalculateModelHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<string>("RATDefaultKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CalculateModelHistoryId");

                    b.HasIndex("RATDefaultKey");

                    b.ToTable("RATHistories");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.History.TotalCostHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<Guid?>("CalculateModelHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Financing")
                        .HasColumnType("real");

                    b.Property<float>("FullTotal")
                        .HasColumnType("real");

                    b.Property<float>("GoesInvisible")
                        .HasColumnType("real");

                    b.Property<float>("GrandTotal")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<float>("Subtotal")
                        .HasColumnType("real");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CalculateModelHistoryId")
                        .IsUnique()
                        .HasFilter("[CalculateModelHistoryId] IS NOT NULL");

                    b.ToTable("TotalCostHistories");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.History.CalculateModelHistory", b =>
                {
                    b.HasOne("GRP.Services.WaterTankCalculator.Entities.Concrete.History.CalculationHistory", "CalculationHistory")
                        .WithMany("CalculateModelHistories")
                        .HasForeignKey("CalculationHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CalculationHistory");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.History.CalculationHistory", b =>
                {
                    b.HasOne("GRP.Services.WaterTankCalculator.Entities.Concrete.History.ConstantsHistory", "ConstantsHistory")
                        .WithOne("CalculationHistory")
                        .HasForeignKey("GRP.Services.WaterTankCalculator.Entities.Concrete.History.CalculationHistory", "ConstantsHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ConstantsHistory");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.History.EdgeModelHistory", b =>
                {
                    b.HasOne("GRP.Services.WaterTankCalculator.Entities.Concrete.History.CalculateModelHistory", "CalculateModelHistory")
                        .WithOne("EdgeModelHistory")
                        .HasForeignKey("GRP.Services.WaterTankCalculator.Entities.Concrete.History.EdgeModelHistory", "CalculateModelHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CalculateModelHistory");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.History.ModuleHistory", b =>
                {
                    b.HasOne("GRP.Services.WaterTankCalculator.Entities.Concrete.History.CalculateModelHistory", "CalculateModelHistory")
                        .WithMany("ModuleHistories")
                        .HasForeignKey("CalculateModelHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GRP.Services.WaterTankCalculator.Entities.Concrete.Defaults.ModuleDefault", "ModuleDefault")
                        .WithMany("ModuleHistories")
                        .HasForeignKey("ModuleDefaultKey")
                        .HasPrincipalKey("Key")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CalculateModelHistory");

                    b.Navigation("ModuleDefault");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.History.ProductHistory", b =>
                {
                    b.HasOne("GRP.Services.WaterTankCalculator.Entities.Concrete.History.CalculateModelHistory", "CalculateModelHistory")
                        .WithMany("ProductHistories")
                        .HasForeignKey("CalculateModelHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GRP.Services.WaterTankCalculator.Entities.Concrete.Defaults.ProductDefault", "ProductDefault")
                        .WithMany("ProductHistories")
                        .HasForeignKey("ProductDefaultKey")
                        .HasPrincipalKey("Key")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CalculateModelHistory");

                    b.Navigation("ProductDefault");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.History.RATHistory", b =>
                {
                    b.HasOne("GRP.Services.WaterTankCalculator.Entities.Concrete.History.CalculateModelHistory", "CalculateModelHistory")
                        .WithMany("RATHistories")
                        .HasForeignKey("CalculateModelHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GRP.Services.WaterTankCalculator.Entities.Concrete.Defaults.RATDefault", "RATDefault")
                        .WithMany("RATHistories")
                        .HasForeignKey("RATDefaultKey")
                        .HasPrincipalKey("Key")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CalculateModelHistory");

                    b.Navigation("RATDefault");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.History.TotalCostHistory", b =>
                {
                    b.HasOne("GRP.Services.WaterTankCalculator.Entities.Concrete.History.CalculateModelHistory", "CalculateModelHistory")
                        .WithOne("TotalCostHistory")
                        .HasForeignKey("GRP.Services.WaterTankCalculator.Entities.Concrete.History.TotalCostHistory", "CalculateModelHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CalculateModelHistory");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.Defaults.ModuleDefault", b =>
                {
                    b.Navigation("ModuleHistories");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.Defaults.ProductDefault", b =>
                {
                    b.Navigation("ProductHistories");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.Defaults.RATDefault", b =>
                {
                    b.Navigation("RATHistories");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.History.CalculateModelHistory", b =>
                {
                    b.Navigation("EdgeModelHistory");

                    b.Navigation("ModuleHistories");

                    b.Navigation("ProductHistories");

                    b.Navigation("RATHistories");

                    b.Navigation("TotalCostHistory");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.History.CalculationHistory", b =>
                {
                    b.Navigation("CalculateModelHistories");
                });

            modelBuilder.Entity("GRP.Services.WaterTankCalculator.Entities.Concrete.History.ConstantsHistory", b =>
                {
                    b.Navigation("CalculationHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
